### ISSUE TITLE
Spostrzeżenia do kodu

### ISSUE THREAD

**Issue by yetem** [BishopKO/qShop#1]
Hej!
Chciałem napisać komentarz pod twoim postem w grupie PythonPoland, ale mnie jeszcze nie dodali do grupy, a boję się że później zapomnę, więc wstawiam tutaj :)

- Tak jak ktoś pisał, dobrze by było poprawić kod by był spójny i zgodny ze standardami. Możesz wypróbować bibliotekę black
https://github.com/python/black
Jej wywołanie automatycznie zreformatuje Ci kod zgodnie ze standardami. Choć niektóre sprawy załatwia inaczej i to już kwestia gustu jak jest lepiej, ale na pewno ułatwi Ci kod

- Zamiast requirements.txt możesz użyć poetry
https://github.com/sdispater/poetry
Do zarządzania bibliotekami w projekcie, od razu da Ci znać jeżeli będą jakieś niespójności i konflikty (choć co prawda u Ciebie jest mało bibliotek więc nie jest to aż tak wymagane)

- Zamiast plików .sh jak migrate.sh itp. możesz spróbować Makefile
https://opensource.com/article/18/8/what-how-makefile
Myślę, że Ci sie spodoba i ułatwi pracę :)

- W niektóre widoki zaczynają się od if smth: potem jest kod i kończy się return Response, ale nie ma przypisanego żadnego warunku kiedy if nie jest spełniony (wywali Ci błąd). Przykład:
qShop_panel/views.py metoda getOrderDetails.
Dużo czytelniejsze jest odwrócenie zależności.
Najpierw zrób if NOT request.POST.get('ajax') i wtedy od razu np. raise Http404, a potem masz już faktyczną logikę, ale jeden poziom wcięć mniej. Dzięki temu od razu widać jaki jest warunek metody (i alternatywny return jest na samej górze co jest bardziej czytelne) a zwykła metoda funkcji nie potrzebuje dodatkowego wcięcia.

- Raz używasz widoków funkcyjnych a raz generycznych w klasach. Jak potrzebujesz używać staff_member_required to możesz je nałożyć na klasę. Jest kilka sposobów na to, tutaj jeden na szybko znaleziony:
https://gist.github.com/tauzen/8752582#file-urls-py-L12
Chodzi głównie o spójność, jak już czegoś używasz to fajnie by było używać wszędzie tego samego sposobu.
Ja osobiście wolę widoki klasowe, bo masz wiele rzeczy generycznie zrobionych, no i możesz używać paradygmatów programowania obiektowego.

**Comment by BishopKO** [comment]
Dzięki wielkie za uwagi. :)
