### ISSUE TITLE
Wykluczające się warunku

### ISSUE THREAD

**Issue by deby22** [BishopKO/qShop#24]
https://github.com/BishopKO/qShop/blob/fd660f8d8cefed884d435969d87f64ecf8044a62/qShop_app/views.py#L15-L17
W pierwszym sprawdzasz czy dany atrybut jest w sesji, następnie przepisujesz jego wartość do zmiennej i sprawdzasz czy tej zmiennej nie ma. Do drugiego warunku nigdy nie wejdzie. 

A nawet gdyby wszedł to trochę słabo bo niżej wykonujesz identyczne zapytanie do bazy:
https://github.com/BishopKO/qShop/blob/fd660f8d8cefed884d435969d87f64ecf8044a62/qShop_app/views.py#L29

**Comment by BishopKO** [comment]
Faktycznie tutaj jakieś dziwne wygibasy porobiłem :)
