### ISSUE TITLE
Wartośc domyślna get przy pobieraniu klucza

### ISSUE THREAD

**Issue by deby22** [BishopKO/qShop#28]
https://github.com/BishopKO/qShop/blob/fd660f8d8cefed884d435969d87f64ecf8044a62/qShop_panel/views.py#L57-L67

Zamiast tych wszystkich warunków możesz po prostu zrobić:
```python
self.request.session['search'] = self.request.session.get('search', self.request.GET.get('search', ''))
```
Zapis może wygląda nieco strasznie ale jak przeczytasz to to zrozumiesz.
Pobierz wartość domyślną z sesji, a jak nie będzie w sesji to z GET. Na końcu przypiszę pusty string.

Nie będziesz wtedy potrzebować inicjalizacji na początku i tych dwóch warunków niżej.

**Comment by BishopKO** [comment]
A nie, self.request.session['search'] = self.request.GET.get('search',  self.request.session.get('search')) ?

**Comment by deby22** [comment]
Znowu masz racje. Nie zawarłeś chyba tylko brzegowego warunku, ze nie będzie nigdzie. Bo domyślnie jest None a pewnie autor chciałby pusty string. 

Zastanawia mnie jednak inna kwestia. Jak przeglądam to ponownie to nigdzie nie widzę pobierania z sesji. Na dobra sprawę wystarczyło by pobieranie z GET

Bo jakie mamy przypadki?
Nie ma klucza w GET ani w sesji - czyścimy 
Nie ma klucza w GET ale jest w sesji - nic nie robimy
Jest pusty klucz w GET - czyścimy
Jest niepusty klucz w GET - ustawiamy

Można zatem to rozbić jeszcze na przypisanie warunkowe. Ale to wszystko delikatnie wpływa na logikę. Dlatego juz sam autor musi się odnieść i ustalić jaki efekt chce osiągnąć

Dlatego jestem zwolennikiem TDD 😉
