### ISSUE TITLE
Jednolinijkowiec, wartość domyślna przy sort.

### ISSUE THREAD

**Issue by deby22** [BishopKO/qShop#30]
https://github.com/BishopKO/qShop/blob/fd660f8d8cefed884d435969d87f64ecf8044a62/qShop_panel/views.py#L166-L169

Ten kod również da się uprościć. Nie dla każdego taki zapis jest czytelny ale warto o nim wiedzieć 

```python
current = request.session.get('current')
form = Order.objects.all() if current else Order.objects.filter(completed=current)

return render(request, "qShop_panel/showOrders.html", {'form': form.order_by(sort)})
```
Przy okazji pomyśl o zmianie nazwy z form na order, bo jest to trochę mylące.

Uporządkuj też cały kod, bo kilka razy nadpisujesz sobie te zmienne i być może cały ten if nie będzie potrzebny?

Kolejne zaproszenie do lektruy na blogu :)
Tym razem mój pierwszy wpis. 
https://ddeby.pl/blog/jednolinijkowce-python-nie-dajmy-sie-zwariowac

**Comment by adam-harmasz** [comment]
Hej, jeśli się nie mylę to ten jednolinijkowiec od kolegi powinien wyglądać tak chyba jeśli chcemy osiągnąć to co było w oryginalnym if/else condition (w ifie statement przyrównywany jest do None):
```
form =  Order.objects.filter(completed=current) if current else Order.objects.all()
```
Dodałbym też jeszcze, że ten jednolinijkowiec to tzw. ternary operator.

**Comment by deby22** [comment]
Tak, masz racje. 

Nie przywykłem do zapisu w którym warunek jest spełniony jeśli zmienna jest None. Trochę takie podwójne zaprzeczenie i moim zdaniem trudno się czyta. Kolejny argument za operatorami warunkowymi. 

I dobrze, ze wspomniałeś. Bo o takie rzeczy mogą zapytać na rozmowie. Często używamy czegoś nie wiedząc nawet jak to się nazywa

**Comment by adam-harmasz** [comment]
No właśnie dobrze kojarzę to określenie bo miałem takie pytanie na rozmowie o pracę :smile: 
Ogólnie to bardzo fajne Code Review zrobiłeś koledze, szanuję!
